<a href="https://colab.research.google.com/github/hferrer08/VIU-Actividad1-AnalisisDatosWeb-Transfermarket/blob/main/Cleaning_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad 1 - Análisis de datos web

## Dataset seleccionado

Football Data from Transfermarkt.

## Objetivo

Analizar información de jugadores, clubes y competiciones para construir un dashboard interactivo en Power BI que permita identificar tendencias relacionadas con el valor de mercado de los jugadores y las características de los clubes.

In [2]:
import pandas as pd

players = pd.read_csv("/players.csv")
clubs = pd.read_csv("/clubs.csv")
competitions = pd.read_csv("/competitions.csv")
valuations = pd.read_csv("/player_valuations.csv")

print("Archivos cargados correctamente")

Archivos cargados correctamente

In [4]:
# Revisamos el tamaño de cada DataFrame.
# El resultado se muestra como (filas, columnas), similar a revisar cuántos registros
# y campos tiene cada tabla.
print("players:", players.shape)
print("clubs:", clubs.shape)
print("competitions:", competitions.shape)
print("valuations:", valuations.shape)

players: (47690, 26)
clubs: (796, 17)
competitions: (67, 11)
valuations: (647626, 6)

In [5]:
# Visualizamos las primeras filas de la tabla de jugadores.
players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [6]:
# Revisamos la estructura de la tabla de jugadores
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47690 entries, 0 to 47689
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             47690 non-null  int64
 1   first_name                            44598 non-null  object
 2   last_name                             47690 non-null  object
 3   name                                  47690 non-null  object
 4   last_season                           47690 non-null  int64
 5   current_club_id                       47690 non-null  int64
 6   player_code                           47690 non-null  object
 7   country_of_birth                      42525 non-null  object
 8   city_of_birth                         42801 non-null  object
 9   country_of_citizenship                47417 non-null  object
 10  date_of_birth                         47641 non-null  object
 11  sub_position                          47225 non-null  object
 12  position                              47690 non-null  object
 13  foot                                  42589 non-null  object
 14  height_in_cm                          44032 non-null  float64
 15  contract_expiration_date              31322 non-null  object
 16  agent_name                            25640 non-null  object
 17  image_url                             47690 non-null  object
 18  international_caps                    17574 non-null  float64
 19  international_goals                   17574 non-null  float64
 20  current_national_team_id              2458 non-null   float64
 21  url                                   47690 non-null  object
 22  current_club_domestic_competition_id  45418 non-null  object
 23  current_club_name                     45418 non-null  object
 24  market_value_in_eur                   41419 non-null  float64
 25  highest_market_value_in_eur           41419 non-null  float64
dtypes: float64(6), int64(3), object(17)
memory usage: 9.5+ MB

In [7]:
# Obtenemos el listado de columnas de cada DataFrame.
# Campos y relaciones entre tablas
print("Columnas players:")
print(players.columns.tolist())

print("\nColumnas clubs:")
print(clubs.columns.tolist())

print("\nColumnas competitions:")
print(competitions.columns.tolist())

print("\nColumnas valuations:")
print(valuations.columns.tolist())

Columnas players:
['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

Columnas clubs:
['club_id', 'club_code', 'name', 'domestic_competition_id', 'total_market_value', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'national_team_players', 'stadium_name', 'stadium_seats', 'net_transfer_record', 'coach_name', 'last_season', 'filename', 'url']

Columnas competitions:
['competition_id', 'competition_code', 'name', 'sub_type', 'type', 'country_id', 'country_name', 'domestic_league_code', 'confederation', 'total_clubs', 'url']

Columnas valuations:
['player_id', 'date', 'market_value_in_eur', 'current_club_name', 'current_club_id', 'player_club_domestic_competition_id']

# Exploración inicial del dataset

En esta sección se cargan los archivos CSV y se analiza su estructura inicial.

Se identifican las tablas principales del modelo de datos:

- Players: información de jugadores.
- Clubs: información de clubes.
- Competitions: información de competiciones.
- Player Valuations: histórico de valor de mercado de los jugadores.

Posteriormente se analizarán los tipos de datos, valores nulos y relaciones entre tablas para preparar la información utilizada en el dashboard de Power BI.

In [10]:
# Analizamos la cantidad de valores nulos presentes en cada tabla
print("Nulos en players:")
print(players.isnull().sum())

print("\nNulos en clubs:")
print(clubs.isnull().sum())

print("\nNulos en competitions:")
print(competitions.isnull().sum())

print("\nNulos en valuations:")
print(valuations.isnull().sum())

Nulos en players:
player_id                                   0
first_name                               3092
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         5165
city_of_birth                            4889
country_of_citizenship                    273
date_of_birth                              49
sub_position                              465
position                                    0
foot                                     5101
height_in_cm                             3658
contract_expiration_date                16368
agent_name                              22050
image_url                                   0
international_caps                      30116
international_goals                     30116
current_national_team_id                45232
url                                         0
current_club_domestic_competition_id     2272
current_club_name                        2272
market_value_in_eur                      6271
highest_market_value_in_eur              6271
dtype: int64

Nulos en clubs:
club_id                      0
club_code                    0
name                         0
domestic_competition_id      0
total_market_value         796
squad_size                   0
average_age                 38
foreigners_number            0
foreigners_percentage       58
national_team_players        0
stadium_name                 0
stadium_seats                0
net_transfer_record          0
coach_name                 706
last_season                  0
filename                     0
url                          0
dtype: int64

Nulos en competitions:
competition_id           0
competition_code         0
name                     0
sub_type                 0
type                     0
country_id               0
country_name            13
domestic_league_code    13
confederation            0
total_clubs             16
url                      0
dtype: int64

Nulos en valuations:
player_id                                  0
date                                       0
market_value_in_eur                        0
current_club_name                          0
current_club_id                            0
player_club_domestic_competition_id    91200
dtype: int64

In [11]:
# Verificamos si existen registros duplicados en cada tabla
print("Duplicados en players:", players.duplicated().sum())
print("Duplicados en clubs:", clubs.duplicated().sum())
print("Duplicados en competitions:", competitions.duplicated().sum())
print("Duplicados en valuations:", valuations.duplicated().sum())

Duplicados en players: 0
Duplicados en clubs: 0
Duplicados en competitions: 0
Duplicados en valuations: 0

In [12]:
# Seleccionamos solo las columnas necesarias para el análisis.
# Esto permite simplificar el modelo de datos y eliminar campos que no aportan valor al dashboard.

players_clean = players[[
    "player_id",
    "name",
    "last_season",
    "current_club_id",
    "country_of_birth",
    "country_of_citizenship",
    "date_of_birth",
    "position",
    "sub_position",
    "foot",
    "height_in_cm",
    "current_club_domestic_competition_id",
    "current_club_name",
    "market_value_in_eur",
    "highest_market_value_in_eur"
]].copy()

clubs_clean = clubs[[
    "club_id",
    "name",
    "domestic_competition_id",
    "squad_size",
    "average_age",
    "foreigners_number",
    "foreigners_percentage",
    "national_team_players",
    "stadium_name",
    "stadium_seats"
]].copy()

competitions_clean = competitions[[
    "competition_id",
    "name",
    "type",
    "country_name",
    "confederation",
    "total_clubs"
]].copy()

valuations_clean = valuations[[
    "player_id",
    "date",
    "market_value_in_eur",
    "current_club_id",
    "current_club_name"
]].copy()

print("Columnas seleccionadas correctamente")

Columnas seleccionadas correctamente

In [13]:
# Revisamos el tamaño de las tablas limpias después de seleccionar las columnas relevantes.

print("players_clean:", players_clean.shape)
print("clubs_clean:", clubs_clean.shape)
print("competitions_clean:", competitions_clean.shape)
print("valuations_clean:", valuations_clean.shape)

players_clean: (47690, 15)
clubs_clean: (796, 10)
competitions_clean: (67, 6)
valuations_clean: (647626, 5)

In [14]:
# Visualizamos los primeros registros de las tablas limpias.
# Esto permite validar rápidamente la estructura y el contenido antes de realizar relaciones entre tablas.

print("PLAYERS")
display(players_clean.head())

print("CLUBS")
display(clubs_clean.head())

print("COMPETITIONS")
display(competitions_clean.head())

print("VALUATIONS")
display(valuations_clean.head())

PLAYERS

,player_id,name,last_season,current_club_id,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,height_in_cm,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav Klose,2015,398,Poland,Germany,1978-06-09 00:00:00,Attack,Centre-Forward,right,184.0,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman Weidenfeller,2017,16,Germany,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar Berbatov,2015,1091,Bulgaria,Bulgaria,1981-01-30 00:00:00,Attack,Centre-Forward,NaN,NaN,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,Lúcio,2012,506,Brazil,Brazil,1978-05-08 00:00:00,Defender,Centre-Back,NaN,NaN,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom Starke,2017,27,East Germany (GDR),Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,L1,FC Bayern München,100000.0,3000000.0

CLUBS

,club_id,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats
0,10,Arminia Bielefeld,L1,27,25.3,15,55.6,4,SchücoArena,26515
1,10004,Paris Football Club,FR1,31,28.7,17,54.8,9,Stade Jean Bouin,19904
2,10010,Esporte Clube Bahia,BRA1,32,26.7,6,18.8,3,Arena Fonte Nova,47364
3,1003,Leicester City,GB1,29,25.9,17,58.6,9,King Power Stadium,32259
4,1005,Unione Sportiva Lecce,IT1,27,25.3,23,85.2,14,Ettore Giardiniero,31559

COMPETITIONS

,competition_id,name,type,country_name,confederation,total_clubs
0,A1,bundesliga,domestic_league,Austria,europa,12.0
1,AFAC,afc-asian-cup,national_team_competition,NaN,asien,NaN
2,AFCN,africa-cup-of-nations,national_team_competition,NaN,afrika,NaN
3,ARG1,torneo-apertura,domestic_league,Argentina,amerika,30.0
4,AUS1,a-league-men,domestic_league,Australia,asien,12.0

VALUATIONS

,player_id,date,market_value_in_eur,current_club_id,current_club_name
0,405973,2000-01-20,150000,3057,Unknown
1,342216,2001-07-20,100000,1241,Unknown
2,3132,2003-12-09,400000,126,Dynamo Kyiv
3,6893,2003-12-15,900000,984,Galatasaray
4,10,2004-10-04,7000000,398,SV Werder Bremen

In [15]:
# Validamos relaciones entre tablas
# Confirmamos cuántos jugadores tienen un club existente en la tabla clubs
# y cuántas valoraciones tienen un jugador existente en la tabla players.

print("Total jugadores:", len(players_clean))
print("Jugadores con club existente en clubs:")
print(players_clean["current_club_id"].isin(clubs_clean["club_id"]).sum())

print("\nTotal valoraciones:", len(valuations_clean))
print("Valoraciones con jugador existente en players:")
print(valuations_clean["player_id"].isin(players_clean["player_id"]).sum())

print("\nClubes con competición existente:")
print(clubs_clean["domestic_competition_id"].isin(competitions_clean["competition_id"]).sum())

Total jugadores: 47690
Jugadores con club existente en clubs:
45418

Total valoraciones: 647626
Valoraciones con jugador existente en players:
647626

Clubes con competición existente:
796

In [16]:
# Construimos una tabla analítica unificando jugadores,
# clubes y competiciones mediante sus relaciones.

players_dashboard = (
    players_clean
    .merge(
        clubs_clean,
        left_on="current_club_id",
        right_on="club_id",
        how="left",
        suffixes=("_player", "_club")
    )
    .merge(
        competitions_clean,
        left_on="domestic_competition_id",
        right_on="competition_id",
        how="left"
    )
)

print("Tabla dashboard creada correctamente")
print(players_dashboard.shape)

Tabla dashboard creada correctamente
(47690, 31)

In [17]:
# Visualizamos los primeros registros de la tabla integrada.

players_dashboard.head()

,player_id,name_player,last_season,current_club_id,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,...,foreigners_percentage,national_team_players,stadium_name,stadium_seats,competition_id,name,type,country_name,confederation,total_clubs
0,10,Miroslav Klose,2015,398,Poland,Germany,1978-06-09 00:00:00,Attack,Centre-Forward,right,...,60.7,11.0,Olimpico di Roma,70634.0,IT1,serie-a,domestic_league,Italy,europa,20.0
1,26,Roman Weidenfeller,2017,16,Germany,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,...,53.8,16.0,SIGNAL IDUNA PARK,81365.0,L1,bundesliga,domestic_league,Germany,europa,18.0
2,65,Dimitar Berbatov,2015,1091,Bulgaria,Bulgaria,1981-01-30 00:00:00,Attack,Centre-Forward,NaN,...,58.1,10.0,Toumba Stadium,28703.0,GR1,super-league-1,domestic_league,Greece,europa,14.0
3,77,Lúcio,2012,506,Brazil,Brazil,1978-05-08 00:00:00,Defender,Centre-Back,NaN,...,72.0,19.0,Allianz Stadium,41507.0,IT1,serie-a,domestic_league,Italy,europa,20.0
4,80,Tom Starke,2017,27,East Germany (GDR),Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,...,52.0,20.0,Allianz Arena,75000.0,L1,bundesliga,domestic_league,Germany,europa,18.0

In [18]:
# Renombramos algunas columnas para que sean más claras en Power BI
# Convertimos la fecha de nacimiento a tipo fecha y calculamos la edad aproximada del jugador

players_dashboard = players_dashboard.rename(columns={
    "name_player": "player_name",
    "name_club": "club_name",
    "name": "competition_name",
    "country_name": "competition_country"
})

players_dashboard["date_of_birth"] = pd.to_datetime(
    players_dashboard["date_of_birth"],
    errors="coerce"
)

players_dashboard["age"] = 2026 - players_dashboard["date_of_birth"].dt.year

print("Columnas renombradas y edad calculada correctamente")

Columnas renombradas y edad calculada correctamente

In [19]:
# Revisamos las columnas finales disponibles para el dashboard.

players_dashboard.columns.tolist()

['player_id',
 'player_name',
 'last_season',
 'current_club_id',
 'country_of_birth',
 'country_of_citizenship',
 'date_of_birth',
 'position',
 'sub_position',
 'foot',
 'height_in_cm',
 'current_club_domestic_competition_id',
 'current_club_name',
 'market_value_in_eur',
 'highest_market_value_in_eur',
 'club_id',
 'club_name',
 'domestic_competition_id',
 'squad_size',
 'average_age',
 'foreigners_number',
 'foreigners_percentage',
 'national_team_players',
 'stadium_name',
 'stadium_seats',
 'competition_id',
 'competition_name',
 'type',
 'competition_country',
 'confederation',
 'total_clubs',
 'age']

In [20]:
# Seleccionamos las columnas finales que se exportarán para Power BI.

dashboard_final = players_dashboard[[
    "player_id",
    "player_name",
    "age",
    "last_season",
    "country_of_birth",
    "country_of_citizenship",
    "position",
    "sub_position",
    "foot",
    "height_in_cm",
    "current_club_id",
    "current_club_name",
    "market_value_in_eur",
    "highest_market_value_in_eur",
    "club_id",
    "squad_size",
    "average_age",
    "foreigners_number",
    "foreigners_percentage",
    "national_team_players",
    "stadium_name",
    "stadium_seats",
    "competition_id",
    "competition_name",
    "type",
    "competition_country",
    "confederation",
    "total_clubs"
]].copy()

dashboard_final.head()

,player_id,player_name,age,last_season,country_of_birth,country_of_citizenship,position,sub_position,foot,height_in_cm,...,foreigners_percentage,national_team_players,stadium_name,stadium_seats,competition_id,competition_name,type,competition_country,confederation,total_clubs
0,10,Miroslav Klose,48.0,2015,Poland,Germany,Attack,Centre-Forward,right,184.0,...,60.7,11.0,Olimpico di Roma,70634.0,IT1,serie-a,domestic_league,Italy,europa,20.0
1,26,Roman Weidenfeller,46.0,2017,Germany,Germany,Goalkeeper,Goalkeeper,left,190.0,...,53.8,16.0,SIGNAL IDUNA PARK,81365.0,L1,bundesliga,domestic_league,Germany,europa,18.0
2,65,Dimitar Berbatov,45.0,2015,Bulgaria,Bulgaria,Attack,Centre-Forward,NaN,NaN,...,58.1,10.0,Toumba Stadium,28703.0,GR1,super-league-1,domestic_league,Greece,europa,14.0
3,77,Lúcio,48.0,2012,Brazil,Brazil,Defender,Centre-Back,NaN,NaN,...,72.0,19.0,Allianz Stadium,41507.0,IT1,serie-a,domestic_league,Italy,europa,20.0
4,80,Tom Starke,45.0,2017,East Germany (GDR),Germany,Goalkeeper,Goalkeeper,right,194.0,...,52.0,20.0,Allianz Arena,75000.0,L1,bundesliga,domestic_league,Germany,europa,18.0

In [22]:
# Exportamos el dataset final limpio en formato CSV.
# Este archivo será cargado posteriormente en Power BI para construir el dashboard.

dashboard_final.to_csv("/dashboard_transfermarkt.csv", index=False)

print("Archivo dashboard_transfermarkt.csv generado correctamente")

Archivo dashboard_transfermarkt.csv generado correctamente

In [23]:
# Revisamos el tamaño final del dataset exportado para Power BI.
print("Dataset final:", dashboard_final.shape)

Dataset final: (47690, 28)

In [24]:
# Revisamos si el dataset final conserva valores nulos después de la preparación.
dashboard_final.isnull().sum()

player_id                         0
player_name                       0
age                              49
last_season                       0
country_of_birth               5165
country_of_citizenship          273
position                          0
sub_position                    465
foot                           5101
height_in_cm                   3658
current_club_id                   0
current_club_name              2272
market_value_in_eur            6271
highest_market_value_in_eur    6271
club_id                        2272
squad_size                     2272
average_age                    4072
foreigners_number              2272
foreigners_percentage          5103
national_team_players          2272
stadium_name                   2272
stadium_seats                  2272
competition_id                 2272
competition_name               2272
type                           2272
competition_country            2272
confederation                  2272
total_clubs                    2272
dtype: int64

In [ ]:
# Reemplazamos valores nulos de texto por "No informado"
# para que Power BI muestre una categoría clara en los filtros y gráficos.

text_columns = [
    "country_of_birth",
    "country_of_citizenship",
    "sub_position",
    "foot",
    "current_club_name",
    "stadium_name",
    "competition_name",
    "type",
    "competition_country",
    "confederation"
]

dashboard_final[text_columns] = dashboard_final[text_columns].fillna("No informado")

# Reemplazamos valores nulos numéricos por 0 cuando representan ausencia de dato.
numeric_columns = [
    "market_value_in_eur",
    "highest_market_value_in_eur",
    "height_in_cm",
    "squad_size",
    "average_age",
    "foreigners_number",
    "foreigners_percentage",
    "national_team_players",
    "stadium_seats",
    "total_clubs"
]

dashboard_final[numeric_columns] = dashboard_final[numeric_columns].fillna(0)

print("Valores nulos tratados correctamente")

Hay jugadores sin club actual, sin valor de mercado, sin pie dominante o sin altura registrada.

In [25]:
# Reemplazamos valores nulos de texto por "No informado"
# para que Power BI muestre una categoría clara en los filtros y gráficos.

text_columns = [
    "country_of_birth",
    "country_of_citizenship",
    "sub_position",
    "foot",
    "current_club_name",
    "stadium_name",
    "competition_name",
    "type",
    "competition_country",
    "confederation"
]

dashboard_final[text_columns] = dashboard_final[text_columns].fillna("No informado")

# Reemplazamos valores nulos numéricos por 0 cuando representan ausencia de dato.
numeric_columns = [
    "market_value_in_eur",
    "highest_market_value_in_eur",
    "height_in_cm",
    "squad_size",
    "average_age",
    "foreigners_number",
    "foreigners_percentage",
    "national_team_players",
    "stadium_seats",
    "total_clubs"
]

dashboard_final[numeric_columns] = dashboard_final[numeric_columns].fillna(0)

print("Valores nulos tratados correctamente")

Valores nulos tratados correctamente

In [26]:
dashboard_final.to_csv("/dashboard_transfermarkt.csv", index=False)
print("Archivo final actualizado correctamente")

Archivo final actualizado correctamente

# Conclusiones de la preparación de datos

Durante el proceso de limpieza y transformación se identificaron valores nulos en algunas columnas relacionadas con información de clubes, competiciones y características de jugadores.

No se detectaron registros duplicados en las tablas analizadas.

Se integraron las tablas de jugadores, clubes y competiciones mediante sus identificadores correspondientes, generando un dataset consolidado de 47.690 registros y 28 variables.

Finalmente, se exportó el conjunto de datos preparado para su posterior análisis y visualización mediante Power BI.